// frontend/src/components/CameraFeed.js

import React, { useState, useRef, useEffect, useCallback } from 'react';
import { supabase } from '../services/supabaseClient';
import { detectRedColor } from '../utils/detection'; // We are importing it from here
import ToggleSwitch from './ToggleSwitch';

const CameraFeed = ({ camera, onDelete }) => {
    const videoRef = useRef(null);
        const canvasRef = useRef(null);
            const [isDetecting, setIsDetecting] = useState(true);
                const [lastAlertTime, setLastAlertTime] = useState(0);

                    const proxiedUrl = `https://cors-anywhere.herokuapp.com/${camera.url}`;

                        const createAlert = useCallback(async (detectionType) => {
                                // Debounce alerts to one every 30 seconds to prevent spam
                                        if (Date.now() - lastAlertTime < 30000) return; 
                                                
                                                        setLastAlertTime(Date.now());
                                                                const { error } = await supabase
                                                                            .from('alerts')
                                                                                        .insert([{ camera_id: camera.id, detection_type: detectionType, status: 'new' }]);
                                                                                                
                                                                                                        if (error) {
                                                                                                                    console.error("Error creating alert in DB:", error.message);
                                                                                                                            }
                                                                                                                                }, [camera.id, lastAlertTime]);

                                                                                                                                    useEffect(() => {
                                                                                                                                            const video = videoRef.current;
                                                                                                                                                    if (!isDetecting || !video) return; // Kill switch / Guard clause

                                                                                                                                                            video.src = proxiedUrl;
                                                                                                                                                                    video.crossOrigin = "Anonymous";
                                                                                                                                                                            video.play().catch(e => console.error("Error playing hidden video:", e));

                                                                                                                                                                                    let animationFrameId;

                                                                                                                                                                                            const processFrame = () => {
                                                                                                                                                                                                        const canvas = canvasRef.current;
                                                                                                                                                                                                                    // Ensure everything is ready before processing
                                                                                                                                                                                                                                if (video.paused || video.ended || !canvas || !isDetecting) {
                                                                                                                                                                                                                                                animationFrameId = requestAnimationFrame(processFrame); // Keep trying
                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                    const ctx = canvas.getContext('2d');
                                                                                                                                                                                                                                                                                                                // Pass createAlert function to the detection utility
                                                                                                                                                                                                                                                                                                                            detectRedColor(ctx, canvas, video, createAlert); 

                                                                                                                                                                                                                                                                                                                                        // This is the loop with a kill switch
                                                                                                                                                                                                                                                                                                                                                    animationFrameId = requestAnimationFrame(processFrame);
                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                            const checkOpenCvReady = setInterval(() => {
                                                                                                                                                                                                                                                                                                                                                                                        if (window.cv && isDetecting) {
                                                                                                                                                                                                                                                                                                                                                                                                        clearInterval(checkOpenCvReady);
                                                                                                                                                                                                                                                                                                                                                                                                                        processFrame();
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                            }, 100);

                                                                                                                                                                                                                                                                                                                                                                                                                                                    // This is the kill switch cleanup function
                                                                                                                                                                                                                                                                                                                                                                                                                                                            return () => { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cancelAnimationFrame(animationFrameId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    clearInterval(checkOpenCvReady);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }, [isDetecting, proxiedUrl, createAlert]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const handleDelete = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (window.confirm(`Delete camera "${camera.name}"?`)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onDelete(camera.id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="camera-feed">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h4>{camera.name}</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <ToggleSwitch isOn={isDetecting} handleToggle={() => setIsDetecting(!isDetecting)} onColor="#0a84ff" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button className="delete-camera-btn" onClick={handleDelete}>×</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <img src={proxiedUrl} alt={`Live feed from ${camera.name}`} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* These are hidden but used for processing */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <video ref={videoRef} style={{ display: 'none' }}></video>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <canvas ref={canvasRef} style={{ display: 'none' }}></canvas>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // ✅ FIX: The duplicate function declaration from below this line has been removed.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default CameraFeed;